// Command f32colorgen writes the sRGB-to-linear lookup table.
//
// Straightening a byte out of the sRGB space is a power function, and there are
// only 256 answers it can ever give. Computing them at startup would put a loop
// of 256 power evaluations in front of the first frame and make the table a
// thing that exists only at runtime, where nothing can read it; computing them
// per call would put one in the rasteriser's path. So they are computed once,
// here, and committed as source that anybody can open and compare.
//
// The output is data. Reviewing it means checking that the numbers did not
// move, which a diff does for free -- so this is run from `go generate` and the
// result is committed, never built on the fly.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"math"
	"os"
)

func main() {
	out := flag.String("out", "", "file to write the table to")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "f32colorgen: %v\n", err)
		os.Exit(1)
	}
}

// run is separated from main so that a failure is a returned error rather than
// a panic. A panic here prints a stack from inside the standard library and
// buries the one line that says which file could not be written.
func run(out string) error {
	if out == "" {
		return errors.New("no output file: pass -out")
	}

	source, err := format.Source(table())
	if err != nil {
		// The unformatted text goes to the error output, because a syntax
		// error in generated source is only findable by reading what was
		// generated.
		os.Stderr.Write(table())
		return fmt.Errorf("the generated source did not parse: %w", err)
	}

	// Source, not a program: 0o644 rather than an executable bit inherited from
	// whatever this was copied from.
	if err := os.WriteFile(out, source, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", out, err)
	}
	return nil
}

// table renders the file, unformatted.
//
// The line break every sixteen entries is what makes the committed file
// reviewable: it puts the table in rows of sixteen, so a value that moved shows
// up on a line of its own instead of inside one line of eight thousand
// characters.
func table() []byte {
	var b bytes.Buffer
	printf := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	printf("// Code generated by f32colorgen. DO NOT EDIT.\n")
	printf("\n")
	printf("package f32color\n\n")

	printf("// table corresponds to sRGBToLinear(float32(index)/0xff)\n")
	printf("var srgb8ToLinear = [...]float32{")
	for v := 0; v <= 0xFF; v++ {
		if v%0x10 == 0 {
			printf("\n\t")
		}
		// %#v prints the shortest decimal that reads back as this exact
		// float32, so the committed constant is the value, not a rounding of
		// it.
		printf("%#v,", sRGBToLinear(float32(v)/0xFF))
	}
	printf("\n}\n")

	return b.Bytes()
}

// sRGBToLinear straightens a channel out of the space a picture is written in.
//
// It is a second copy of the function of the same name in the package this
// writes into, and it has to be: importing that package means compiling the
// table this is about to replace, so a table that failed to compile could never
// be regenerated. Two copies of one formula drift, silently -- so the package
// carries a test that fails if the table stops agreeing with its own function,
// which is the gate this duplication is allowed under.
func sRGBToLinear(c float32) float32 {
	if c <= 0.04045 {
		return c / 12.92
	}
	return float32(math.Pow(float64((c+0.055)/1.055), 2.4))
}
