// Code generated by internal/tokengen from theme/basecoat/base.css. DO NOT EDIT.

package theme

import "image/color"

// Palette is the colour of every named surface, in one scheme.
//
// The names are the ones the stylesheet declares, so a colour called the
// same thing on both halves of the product is the same colour.
type Palette struct {
	Accent                   color.NRGBA
	AccentForeground         color.NRGBA
	Background               color.NRGBA
	Border                   color.NRGBA
	Card                     color.NRGBA
	CardForeground           color.NRGBA
	Chart1                   color.NRGBA
	Chart2                   color.NRGBA
	Chart3                   color.NRGBA
	Chart4                   color.NRGBA
	Chart5                   color.NRGBA
	Destructive              color.NRGBA
	Foreground               color.NRGBA
	Input                    color.NRGBA
	Muted                    color.NRGBA
	MutedForeground          color.NRGBA
	Popover                  color.NRGBA
	PopoverForeground        color.NRGBA
	Primary                  color.NRGBA
	PrimaryForeground        color.NRGBA
	Ring                     color.NRGBA
	ScrollbarThumb           color.NRGBA
	ScrollbarTrack           color.NRGBA
	Secondary                color.NRGBA
	SecondaryForeground      color.NRGBA
	Sidebar                  color.NRGBA
	SidebarAccent            color.NRGBA
	SidebarAccentForeground  color.NRGBA
	SidebarBorder            color.NRGBA
	SidebarForeground        color.NRGBA
	SidebarPrimary           color.NRGBA
	SidebarPrimaryForeground color.NRGBA
	SidebarRing              color.NRGBA
}

// Metrics are the lengths the stylesheet declares, in points.
type Metrics struct {
	Radius             float32
	ScrollbarRadius    float32
	ScrollbarSmWidth   float32
	ScrollbarWidth     float32
	SidebarMobileWidth float32
	SidebarWidth       float32
}

var lightPalette = Palette{
	Accent:                   color.NRGBA{R: 245, G: 245, B: 245, A: 255},
	AccentForeground:         color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	Background:               color.NRGBA{R: 255, G: 255, B: 255, A: 255},
	Border:                   color.NRGBA{R: 229, G: 229, B: 229, A: 255},
	Card:                     color.NRGBA{R: 255, G: 255, B: 255, A: 255},
	CardForeground:           color.NRGBA{R: 10, G: 10, B: 10, A: 255},
	Chart1:                   color.NRGBA{R: 147, G: 197, B: 253, A: 255},
	Chart2:                   color.NRGBA{R: 59, G: 130, B: 246, A: 255},
	Chart3:                   color.NRGBA{R: 37, G: 99, B: 235, A: 255},
	Chart4:                   color.NRGBA{R: 29, G: 78, B: 216, A: 255},
	Chart5:                   color.NRGBA{R: 30, G: 64, B: 175, A: 255},
	Destructive:              color.NRGBA{R: 231, G: 0, B: 11, A: 255},
	Foreground:               color.NRGBA{R: 10, G: 10, B: 10, A: 255},
	Input:                    color.NRGBA{R: 229, G: 229, B: 229, A: 255},
	Muted:                    color.NRGBA{R: 245, G: 245, B: 245, A: 255},
	MutedForeground:          color.NRGBA{R: 115, G: 115, B: 115, A: 255},
	Popover:                  color.NRGBA{R: 255, G: 255, B: 255, A: 255},
	PopoverForeground:        color.NRGBA{R: 10, G: 10, B: 10, A: 255},
	Primary:                  color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	PrimaryForeground:        color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	Ring:                     color.NRGBA{R: 161, G: 161, B: 161, A: 255},
	ScrollbarThumb:           color.NRGBA{R: 229, G: 229, B: 229, A: 255},
	ScrollbarTrack:           color.NRGBA{R: 0, G: 0, B: 0, A: 0},
	Secondary:                color.NRGBA{R: 245, G: 245, B: 245, A: 255},
	SecondaryForeground:      color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	Sidebar:                  color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	SidebarAccent:            color.NRGBA{R: 245, G: 245, B: 245, A: 255},
	SidebarAccentForeground:  color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	SidebarBorder:            color.NRGBA{R: 229, G: 229, B: 229, A: 255},
	SidebarForeground:        color.NRGBA{R: 10, G: 10, B: 10, A: 255},
	SidebarPrimary:           color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	SidebarPrimaryForeground: color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	SidebarRing:              color.NRGBA{R: 161, G: 161, B: 161, A: 255},
}

var darkPalette = Palette{
	Accent:                   color.NRGBA{R: 64, G: 64, B: 64, A: 255},
	AccentForeground:         color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	Background:               color.NRGBA{R: 10, G: 10, B: 10, A: 255},
	Border:                   color.NRGBA{R: 255, G: 255, B: 255, A: 26},
	Card:                     color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	CardForeground:           color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	Chart1:                   color.NRGBA{R: 147, G: 197, B: 253, A: 255},
	Chart2:                   color.NRGBA{R: 59, G: 130, B: 246, A: 255},
	Chart3:                   color.NRGBA{R: 37, G: 99, B: 235, A: 255},
	Chart4:                   color.NRGBA{R: 29, G: 78, B: 216, A: 255},
	Chart5:                   color.NRGBA{R: 30, G: 64, B: 175, A: 255},
	Destructive:              color.NRGBA{R: 255, G: 100, B: 103, A: 255},
	Foreground:               color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	Input:                    color.NRGBA{R: 255, G: 255, B: 255, A: 38},
	Muted:                    color.NRGBA{R: 38, G: 38, B: 38, A: 255},
	MutedForeground:          color.NRGBA{R: 161, G: 161, B: 161, A: 255},
	Popover:                  color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	PopoverForeground:        color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	Primary:                  color.NRGBA{R: 229, G: 229, B: 229, A: 255},
	PrimaryForeground:        color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	Ring:                     color.NRGBA{R: 115, G: 115, B: 115, A: 255},
	ScrollbarThumb:           color.NRGBA{R: 255, G: 255, B: 255, A: 26},
	ScrollbarTrack:           color.NRGBA{R: 0, G: 0, B: 0, A: 0},
	Secondary:                color.NRGBA{R: 38, G: 38, B: 38, A: 255},
	SecondaryForeground:      color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	Sidebar:                  color.NRGBA{R: 23, G: 23, B: 23, A: 255},
	SidebarAccent:            color.NRGBA{R: 38, G: 38, B: 38, A: 255},
	SidebarAccentForeground:  color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	SidebarBorder:            color.NRGBA{R: 255, G: 255, B: 255, A: 26},
	SidebarForeground:        color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	SidebarPrimary:           color.NRGBA{R: 20, G: 71, B: 230, A: 255},
	SidebarPrimaryForeground: color.NRGBA{R: 250, G: 250, B: 250, A: 255},
	SidebarRing:              color.NRGBA{R: 82, G: 82, B: 82, A: 255},
}

var metrics = Metrics{
	Radius:             10,
	ScrollbarRadius:    9999,
	ScrollbarSmWidth:   6,
	ScrollbarWidth:     10,
	SidebarMobileWidth: 288,
	SidebarWidth:       256,
}
